let audienceImportRows=[];
function downloadAudienceTemplate(){
 const csv='nombre,poblacion,impacto,barreras\r\nLíderes,35,Alto,Disponibilidad\r\nOperaciones,120,Medio,Capacitación';
 const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});
 const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='HACERLO_plantilla_audiencias.csv';a.click();URL.revokeObjectURL(url);
}
function parseAudienceCSV(text){
 text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}
 else if(c===','&&!quoted){row.push(cell.trim());cell=''}
 else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);row=[];cell=''}else cell+=c}
 if(quoted)throw Error('Hay comillas sin cerrar en el archivo');row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);
 return rows;
}
async function previewAudienceCSV(input){
 const target=document.getElementById('audience-import-preview');audienceImportRows=[];
 if(!input.files.length)return;
 try{
 const file=input.files[0];if(file.size>2e6)throw Error('El archivo supera 2 MB');
 const lines=parseAudienceCSV(await file.text());if(lines.length<2)throw Error('No hay filas para importar');
 const headers=lines.shift().map(x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim());
 if(!['nombre','poblacion','impacto','barreras'].every(h=>headers.includes(h)))throw Error('Encabezados requeridos: nombre,poblacion,impacto,barreras');
 if(lines.length>2000)throw Error('Máximo 2.000 audiencias por archivo');
 const existing=new Set(current().audiences.map(a=>a.name.trim().toLocaleLowerCase('es'))),seen=new Set();
 audienceImportRows=lines.map((line,index)=>{
 let obj=Object.fromEntries(headers.map((h,i)=>[h,(line[i]||'').trim()]));
 let key=obj.nombre.toLocaleLowerCase('es'),pop=obj.poblacion;
 let errors=[];if(!obj.nombre)errors.push('Nombre vacío');if(pop&&!/^[0-9]+$/.test(pop))errors.push('Población inválida');
 if(obj.impacto&&!['Alto','Medio','Bajo'].includes(obj.impacto))errors.push('Impacto debe ser Alto, Medio o Bajo');
 if(seen.has(key))errors.push('Duplicada dentro del archivo');seen.add(key);
 return {row:index+2,name:obj.nombre,population:pop,impact:obj.impacto,barriers:obj.barreras,existing:existing.has(key),errors};
 });
 let valid=audienceImportRows.filter(r=>!r.errors.length);
 target.innerHTML=`<p>${valid.length} registros válidos; ${audienceImportRows.length-valid.length} con errores; ${valid.filter(r=>r.existing).length} existentes.</p>`+
 `<div style="max-height:270px;overflow:auto"><table><tr><th>Fila</th><th>Audiencia</th><th>Población</th><th>Impacto</th><th>Resultado</th></tr>`+
 audienceImportRows.map(r=>`<tr><td>${r.row}</td><td>${safe(r.name)}</td><td>${safe(r.population)}</td><td>${safe(r.impact)}</td><td>${r.errors.length?safe(r.errors.join('; ')):r.existing?'Existente':'Nueva'}</td></tr>`).join('')+'</table></div>'+
 `<label>Registros existentes<select id="audience-duplicate-mode"><option value="skip">Omitir (conservar datos actuales)</option><option value="update">Actualizar con valores importados</option></select></label>`+
 `<button type="button" class="primary" ${valid.length?'':'disabled'} onclick="commitAudienceImport()">Importar ${valid.length} registros válidos</button>`;
 }catch(e){target.textContent='Error: '+e.message}
}
function commitAudienceImport(){
 let x=current(),mode=document.getElementById('audience-duplicate-mode').value,added=0,updated=0,skipped=0;
 for(let r of audienceImportRows.filter(r=>!r.errors.length)){
 let old=x.audiences.find(a=>a.name.trim().toLocaleLowerCase('es')===r.name.trim().toLocaleLowerCase('es'));
 if(old&&mode==='skip'){skipped++;continue}
 if(old){Object.assign(old,{population:r.population,impact:r.impact,barriers:r.barriers});updated++}
 else{x.audiences.push({id:'aud-'+Date.now()+'-'+added+'-'+Math.random().toString(36).slice(2,7),name:r.name,population:r.population,impact:r.impact,barriers:r.barriers});added++}
 }
 save();alert(`Importación terminada: ${added} nuevas, ${updated} actualizadas, ${skipped} omitidas. Las filas con errores no se importaron.`);audienceImportRows=[];render();
}

function audienceChecks(x){return x.audiences.length?x.audiences.map(a=>`<label style="display:block"><input style="width:auto" type="checkbox" name="audienceIds" value="${a.id}"> ${safe(a.name)}</label>`).join(''):'<p class="muted">Crea una audiencia antes de seleccionar.</p>'}
function audienceForm(){return `<div class="panel"><h3>Nueva audiencia</h3><div class="audience-fields"><input data-field="name" required placeholder="Nombre de la audiencia"><input data-field="population" type="number" min="0" placeholder="Número de personas"><select data-field="impact"><option value="">Impacto sin evaluar</option><option>Alto</option><option>Medio</option><option>Bajo</option></select><textarea data-field="barriers" placeholder="Barreras y facilitadores (opcional)"></textarea><button type="button" class="primary" onclick="addAudienceFromButton(this)">Guardar audiencia</button></div></div>`}
function audienceList(x){return x.audiences.length?x.audiences.map(a=>`<div class="panel"><strong>${safe(a.name)}</strong><p class="muted">${safe(a.population||'—')} personas · Impacto: ${safe(a.impact||'Sin evaluar')}</p></div>`).join(''):'<div class="empty">No hay audiencias registradas.</div>'}
function behaviorAudienceLabel(x,b){return b.scope!=='specific'?'Todas las audiencias':(b.audienceIds||[]).map(id=>x.audiences.find(a=>a.id===id)?.name||'Audiencia eliminada').map(safe).join(', ')||'Sin audiencia seleccionada'}
function showAudienceForm(id){$(id).classList.toggle('hide')}
function addAudienceFromButton(button){let fields=button.closest(".audience-fields");let a=Object.fromEntries([...fields.querySelectorAll("[data-field]")].map(el=>[el.dataset.field,el.value]));if(!a.name.trim())return alert("Indica el nombre de la audiencia");a.id='aud-'+Date.now();current().audiences.push(a);save();render()}

// HACERLO V2.2: clasificación configurable, con reglas explícitas (no inferencias sobre personas).
const AUD_AUTH={'Decisor':10,'Influenciador Directo':9,'Influenciador Indirecto':8,'Espectador':5};
const AUD_POSITION={'Promotor':10,'Pasivo':8,'Probable Resistente':6,'Saboteador Abierto':5,'Saboteador Oculto':4};
const AUD_STRATEGIES={Q1:['Cocrear decisiones clave','Patrocinio visible','Involucrar en diseño y validación'],Q2:['Consultas ejecutivas puntuales','Validación de decisiones clave','Negociación y manejo de expectativas'],Q3:['Comunicaciones generales','Actualizaciones periódicas','Monitorear cambios de interés'],Q4:['Escucha activa','Talleres, pilotos y grupos focales','Espacios de retroalimentación']};
let audienceTab='registro',audienceEditing=null,audienceFilter='';
function audScore(a){return {authority:AUD_AUTH[a.authority]??null,interest:AUD_POSITION[a.position]??null}}
function audQuadrant(a){let s=audScore(a);if(s.authority===null||s.interest===null)return null;return `Q${s.authority>=7?(s.interest>=7?1:2):(s.interest>=7?4:3)}`}
function audSelect(field,values,value){return `<select name="${field}"><option value="">Sin clasificar</option>${Object.keys(values).map(k=>`<option ${value===k?'selected':''}>${safe(k)}</option>`).join('')}</select>`}
function audInput(label,field,value='',type='text'){return `<label>${label}<input type="${type}" name="${field}" value="${safe(value)}"></label>`}
function audienceManagementPage(x){let rows=x.audiences||[],counts={Q1:0,Q2:0,Q3:0,Q4:0};rows.forEach(a=>{let q=audQuadrant(a);if(q)counts[q]+=a.kind==='Grupo'?Number(a.population)||0:1});return `<section class="panel"><h2>Gestión estratégica de audiencias</h2><p class="muted">Registra personas o grupos, identifica su participación y explora estrategias. Las categorías son valoraciones de trabajo, no diagnósticos personales.</p><div class="flex"><button class="${audienceTab==='registro'?'primary':'secondary'}" onclick="audienceTab='registro';render()">Registro</button><button class="${audienceTab==='mapa'?'primary':'secondary'}" onclick="audienceTab='mapa';render()">Mapa de audiencias</button><button class="${audienceTab==='estrategias'?'primary':'secondary'}" onclick="audienceTab='estrategias';render()">Estrategias</button></div></section>${audienceTab==='registro'?audienceRegistration(x):audienceTab==='mapa'?audienceMap(x,counts):audienceStrategies(x,counts)}`}
function audienceRegistration(x){let a=x.audiences.find(a=>a.id===audienceEditing)||{};return `<div class="grid"><section class="panel"><h2>${audienceEditing?'Editar':'Registrar'} audiencia</h2><form onsubmit="saveAudienceV22(event)"><div class="aud-v22-fields"><label>Tipo<select name="kind"><option ${a.kind!=='Grupo'?'selected':''}>Persona</option><option ${a.kind==='Grupo'?'selected':''}>Grupo</option></select></label>${audInput('Nombre / grupo *','name',a.name)}${audInput('Número de personas (grupos)','population',a.population||'','number')}${audInput('Cargo','job',a.job)}${audInput('Dirección','direction',a.direction)}${audInput('Equipo','team',a.team)}${audInput('Correo (opcional)','email',a.email,'email')}<label>Rol dentro del cambio<input name="changeRole" value="${safe(a.changeRole)}" placeholder="Ej. Líder, ejecutor, usuario"></label><label>Autoridad${audSelect('authority',AUD_AUTH,a.authority)}</label><label>Interés/influencia${audSelect('position',AUD_POSITION,a.position)}</label><label>Impacto<select name="impact"><option value="">Sin evaluar</option>${['Alto','Medio','Bajo'].map(v=>`<option ${a.impact===v?'selected':''}>${v}</option>`).join('')}</select></label>${audInput('Segmento','segment',a.segment)}</div><label>Impactos específicos<textarea name="specificImpact">${safe(a.specificImpact)}</textarea></label><label>Historial de cambio<textarea name="changeHistory">${safe(a.changeHistory)}</textarea></label><label>Evidencias de clasificación (opcional)<textarea name="classificationEvidence" placeholder="Hechos observados, fuente y fecha">${safe(a.classificationEvidence)}</textarea></label><button class="primary">${audienceEditing?'Guardar cambios':'Agregar audiencia'}</button> ${audienceEditing?'<button type="button" class="secondary" onclick="audienceEditing=null;render()">Cancelar</button>':''}</form></section><section class="panel"><h2>Carga masiva CSV</h2><p class="muted">Descarga una plantilla con categorías seleccionables y conserva la información existente. La importación admite columnas adicionales.</p><button class="secondary" onclick="downloadAudienceTemplateV22()">↓ Plantilla CSV</button><input type="file" accept=".csv,text/csv" onchange="previewAudienceCSVV22(this)"><div id="aud-v22-import"></div><h3>Audiencias (${x.audiences.length})</h3><div class="aud-v22-list">${x.audiences.map(a=>`<div class="aud-v22-row"><div><strong>${safe(a.name)}</strong><p class="muted">${safe(a.authority||'Sin autoridad')} · ${safe(a.position||'Sin posición')} · ${audQuadrant(a)||'Sin cuadrante'}</p></div><button class="secondary" onclick="audienceEditing='${safe(a.id)}';render()">Editar</button></div>`).join('')||'<div class="empty">No hay audiencias registradas.</div>'}</div></section></div>`}
function saveAudienceV22(e){e.preventDefault();let f=e.target,d=Object.fromEntries(new FormData(f));if(!d.name.trim())return alert('Indica un nombre');if(d.population&&(!Number.isInteger(Number(d.population))||Number(d.population)<0))return alert('La población debe ser un entero no negativo');let x=current(),a=x.audiences.find(a=>a.id===audienceEditing);if(!a){a={id:'aud-'+crypto.randomUUID()};x.audiences.push(a)}Object.assign(a,d,{name:d.name.trim()});audienceEditing=null;save();render()}
function audienceMap(x,counts){let positioned=x.audiences.filter(a=>audQuadrant(a)),unclassified=x.audiences.length-positioned.length;let dots=positioned.map((a,i)=>{let s=audScore(a),px=12+(s.interest-4)/6*76,py=88-(s.authority-5)/5*76;let offset=(i%5-2)*1.7;return `<button class="aud-dot" style="left:${Math.max(3,Math.min(94,px+offset))}%;top:${Math.max(4,Math.min(94,py+offset))}%;background:${a.position==='Promotor'?'#15b9a3':a.position==='Pasivo'?'#dfad51':'#e67d70'}" title="${safe(a.name)}: ${safe(a.authority)} / ${safe(a.position)}" onclick="alert('${safe(a.name).replace(/'/g,'')} · ${audQuadrant(a)}')" aria-label="${safe(a.name)}"></button>`}).join('');return `<section class="panel"><h2>Mapa de autoridad e interés/influencia</h2><p class="muted">Corte alto: 7 puntos. Valores calculados automáticamente según tus categorías. Cada punto representa un registro; las cantidades por cuadrante suman personas estimadas para los grupos.</p><div class="aud-map"><div class="aud-map-quadrants"><div>Q2 · Consultar <strong>${counts.Q2}</strong></div><div>Q1 · Colaborar <strong>${counts.Q1}</strong></div><div>Q3 · Informar <strong>${counts.Q3}</strong></div><div>Q4 · Involucrar <strong>${counts.Q4}</strong></div></div>${dots}</div><p class="muted">↑ Autoridad · → Interés/influencia · Sin clasificar: ${unclassified} registros</p><div class="aud-v22-list">${x.audiences.map(a=>`<div class="aud-v22-row"><span>${safe(a.name)}</span><span>${audQuadrant(a)||'Sin clasificar'} · ${audScore(a).authority??'—'} / ${audScore(a).interest??'—'}</span></div>`).join('')}</div></section>`}
function audienceStrategies(x,counts){return `<section class="panel"><h2>Estrategias por cuadrante</h2><p class="muted">Orientaciones iniciales: contrasta las acciones con el diagnóstico y la evidencia antes de aplicarlas.</p><div class="grid">${Object.entries(AUD_STRATEGIES).map(([q,items])=>`<section class="panel"><h3>${q} · ${{Q1:'Colaborar',Q2:'Consultar',Q3:'Informar',Q4:'Involucrar'}[q]} (${counts[q]})</h3>${items.map(t=>`<p>• ${safe(t)}</p>`).join('')}</section>`).join('')}</div><h3>Audiencias y recomendaciones</h3>${x.audiences.map(a=>{let q=audQuadrant(a);return `<div class="aud-v22-row"><div><strong>${safe(a.name)}</strong><p class="muted">${q||'Pendiente de clasificación'} · ${safe(a.position||'Sin posición')}</p></div><span>${q?AUD_STRATEGIES[q].map(safe).join(' · '):'Selecciona las categorías para obtener una orientación.'}</span></div>`}).join('')}</section>`}
const AUD_CSV_FIELDS=['nombre','tipo','poblacion','cargo','direccion','equipo','correo','rol_cambio','autoridad','interes_influencia','impacto','segmento','impactos_especificos','historial_cambio','evidencia'];
function downloadAudienceTemplateV22(){let header=AUD_CSV_FIELDS.join(','),example=['Líderes regionales','Grupo','12','Líder','Operaciones','Regional','','Patrocinador','Decisor','Promotor','Alto','','','',''].join(',');let b=new Blob(['\uFEFF'+header+'\r\n'+example],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='HACERLO_plantilla_audiencias_V22.csv';a.click();URL.revokeObjectURL(url)}
let audV22Rows=[];
async function previewAudienceCSVV22(input){let target=document.getElementById('aud-v22-import');audV22Rows=[];if(!input.files.length)return;try{let file=input.files[0];if(file.size>2e6)throw Error('Máximo 2 MB');let lines=parseAudienceCSV(await file.text());if(lines.length<2)throw Error('El archivo no tiene registros');let keys=lines.shift().map(v=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/[\s/]+/g,'_'));if(!keys.includes('nombre'))throw Error('Falta columna nombre');if(lines.length>2000)throw Error('Máximo 2000 registros');let seen=new Set();audV22Rows=lines.map((line,i)=>{let d=Object.fromEntries(keys.map((k,j)=>[k,(line[j]||'').trim()]));let errors=[];if(!d.nombre)errors.push('Nombre vacío');if(seen.has(d.nombre.toLowerCase()))errors.push('Nombre repetido');seen.add(d.nombre.toLowerCase());if(d.autoridad&&!Object.hasOwn(AUD_AUTH,d.autoridad))errors.push('Autoridad no reconocida');if(d.interes_influencia&&!Object.hasOwn(AUD_POSITION,d.interes_influencia))errors.push('Interés/influencia no reconocido');if(d.poblacion&&(!/^\d+$/.test(d.poblacion)))errors.push('Población inválida');return {d,errors,line:i+2}});let valid=audV22Rows.filter(r=>!r.errors.length);target.innerHTML=`<p>${valid.length} filas válidas · ${audV22Rows.length-valid.length} con errores</p>${audV22Rows.filter(r=>r.errors.length).slice(0,10).map(r=>`<p class="notice">Fila ${r.line}: ${safe(r.errors.join(', '))}</p>`).join('')}<label>Duplicados por nombre<select id="aud-v22-mode"><option value="skip">Omitir existentes</option><option value="update">Actualizar existentes</option></select></label><button class="primary" ${valid.length?'':'disabled'} onclick="commitAudienceCSVV22()">Importar ${valid.length}</button>`}catch(e){target.textContent='Error: '+e.message}}
function commitAudienceCSVV22(){let x=current(),mode=document.getElementById('aud-v22-mode').value,added=0,updated=0;let map={nombre:'name',tipo:'kind',poblacion:'population',cargo:'job',direccion:'direction',equipo:'team',correo:'email',rol_cambio:'changeRole',autoridad:'authority',interes_influencia:'position',impacto:'impact',segmento:'segment',impactos_especificos:'specificImpact',historial_cambio:'changeHistory',evidencia:'classificationEvidence'};for(let {d,errors} of audV22Rows){if(errors.length)continue;let a=x.audiences.find(a=>a.name.toLowerCase()===d.nombre.toLowerCase());if(a&&mode==='skip')continue;if(!a){a={id:'aud-'+crypto.randomUUID()};x.audiences.push(a);added++}else updated++;for(let [from,to] of Object.entries(map))if(d[from]!==undefined)a[to]=d[from]}audV22Rows=[];save();alert(`Importadas: ${added} nuevas, ${updated} actualizadas`);render()}
