let audienceImportRows=[];
function downloadAudienceTemplate(){
 const csv='nombre,poblacion,impacto,barreras\r\nLíderes,35,Alto,Disponibilidad\r\nOperaciones,120,Medio,Capacitación';
 const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});
 const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='HACERLO_plantilla_audiencias.csv';a.click();URL.revokeObjectURL(url);
}
function parseAudienceCSV(text){
 text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}
 else if(c===','&&!quoted){row.push(cell.trim());cell=''}
 else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);row=[];cell=''}else cell+=c}
 if(quoted)throw Error('Hay comillas sin cerrar en el archivo');row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);
 return rows;
}
async function previewAudienceCSV(input){
 const target=document.getElementById('audience-import-preview');audienceImportRows=[];
 if(!input.files.length)return;
 try{
 const file=input.files[0];if(file.size>2e6)throw Error('El archivo supera 2 MB');
 const lines=parseAudienceCSV(await file.text());if(lines.length<2)throw Error('No hay filas para importar');
 const headers=lines.shift().map(x=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim());
 if(!['nombre','poblacion','impacto','barreras'].every(h=>headers.includes(h)))throw Error('Encabezados requeridos: nombre,poblacion,impacto,barreras');
 if(lines.length>2000)throw Error('Máximo 2.000 audiencias por archivo');
 const existing=new Set(current().audiences.map(a=>a.name.trim().toLocaleLowerCase('es'))),seen=new Set();
 audienceImportRows=lines.map((line,index)=>{
 let obj=Object.fromEntries(headers.map((h,i)=>[h,(line[i]||'').trim()]));
 let key=obj.nombre.toLocaleLowerCase('es'),pop=obj.poblacion;
 let errors=[];if(!obj.nombre)errors.push('Nombre vacío');if(pop&&!/^[0-9]+$/.test(pop))errors.push('Población inválida');
 if(obj.impacto&&!['Alto','Medio','Bajo'].includes(obj.impacto))errors.push('Impacto debe ser Alto, Medio o Bajo');
 if(seen.has(key))errors.push('Duplicada dentro del archivo');seen.add(key);
 return {row:index+2,name:obj.nombre,population:pop,impact:obj.impacto,barriers:obj.barreras,existing:existing.has(key),errors};
 });
 let valid=audienceImportRows.filter(r=>!r.errors.length);
 target.innerHTML=`<p>${valid.length} registros válidos; ${audienceImportRows.length-valid.length} con errores; ${valid.filter(r=>r.existing).length} existentes.</p>`+
 `<div style="max-height:270px;overflow:auto"><table><tr><th>Fila</th><th>Audiencia</th><th>Población</th><th>Impacto</th><th>Resultado</th></tr>`+
 audienceImportRows.map(r=>`<tr><td>${r.row}</td><td>${safe(r.name)}</td><td>${safe(r.population)}</td><td>${safe(r.impact)}</td><td>${r.errors.length?safe(r.errors.join('; ')):r.existing?'Existente':'Nueva'}</td></tr>`).join('')+'</table></div>'+
 `<label>Registros existentes<select id="audience-duplicate-mode"><option value="skip">Omitir (conservar datos actuales)</option><option value="update">Actualizar con valores importados</option></select></label>`+
 `<button type="button" class="primary" ${valid.length?'':'disabled'} onclick="commitAudienceImport()">Importar ${valid.length} registros válidos</button>`;
 }catch(e){target.textContent='Error: '+e.message}
}
function commitAudienceImport(){
 let x=current(),mode=document.getElementById('audience-duplicate-mode').value,added=0,updated=0,skipped=0;
 for(let r of audienceImportRows.filter(r=>!r.errors.length)){
 let old=x.audiences.find(a=>a.name.trim().toLocaleLowerCase('es')===r.name.trim().toLocaleLowerCase('es'));
 if(old&&mode==='skip'){skipped++;continue}
 if(old){Object.assign(old,{population:r.population,impact:r.impact,barriers:r.barriers});updated++}
 else{x.audiences.push({id:'aud-'+Date.now()+'-'+added+'-'+Math.random().toString(36).slice(2,7),name:r.name,population:r.population,impact:r.impact,barriers:r.barriers});added++}
 }
 save();alert(`Importación terminada: ${added} nuevas, ${updated} actualizadas, ${skipped} omitidas. Las filas con errores no se importaron.`);audienceImportRows=[];render();
}

function audienceChecks(x){return x.audiences.length?x.audiences.map(a=>`<label style="display:block"><input style="width:auto" type="checkbox" name="audienceIds" value="${a.id}"> ${safe(a.name)}</label>`).join(''):'<p class="muted">Crea una audiencia antes de seleccionar.</p>'}
function audienceForm(){return `<div class="panel"><h3>Nueva audiencia</h3><div class="audience-fields"><input data-field="name" required placeholder="Nombre de la audiencia"><input data-field="population" type="number" min="0" placeholder="Número de personas"><select data-field="impact"><option value="">Impacto sin evaluar</option><option>Alto</option><option>Medio</option><option>Bajo</option></select><textarea data-field="barriers" placeholder="Barreras y facilitadores (opcional)"></textarea><button type="button" class="primary" onclick="addAudienceFromButton(this)">Guardar audiencia</button></div></div>`}
function audienceList(x){return x.audiences.length?x.audiences.map(a=>`<div class="panel"><strong>${safe(a.name)}</strong><p class="muted">${safe(a.population||'—')} personas · Impacto: ${safe(a.impact||'Sin evaluar')}</p></div>`).join(''):'<div class="empty">No hay audiencias registradas.</div>'}
function behaviorAudienceLabel(x,b){return b.scope!=='specific'?'Todas las audiencias':(b.audienceIds||[]).map(id=>x.audiences.find(a=>a.id===id)?.name||'Audiencia eliminada').map(safe).join(', ')||'Sin audiencia seleccionada'}
function showAudienceForm(id){$(id).classList.toggle('hide')}
function addAudienceFromButton(button){let fields=button.closest(".audience-fields");let a=Object.fromEntries([...fields.querySelectorAll("[data-field]")].map(el=>[el.dataset.field,el.value]));if(!a.name.trim())return alert("Indica el nombre de la audiencia");a.id='aud-'+Date.now();current().audiences.push(a);save();render()}

// HACERLO V2.2: clasificación configurable, con reglas explícitas (no inferencias sobre personas).
const AUD_AUTH={'Decisor':10,'Influenciador Directo':9,'Influenciador Indirecto':8,'Espectador':5};
const AUD_POSITION={'Promotor':10,'Pasivo':8,'Probable Resistente':6,'Saboteador Abierto':5,'Saboteador Oculto':4};
const AUD_STRATEGIES={Q1:['Cocrear decisiones clave','Patrocinio visible','Involucrar en diseño y validación'],Q2:['Consultas ejecutivas puntuales','Validación de decisiones clave','Negociación y manejo de expectativas'],Q3:['Comunicaciones generales','Actualizaciones periódicas','Monitorear cambios de interés'],Q4:['Escucha activa','Talleres, pilotos y grupos focales','Espacios de retroalimentación']};
let audienceTab='registro',audienceEditing=null,audienceFilter='',audienceSelected=null,audienceQuadrantFilter='';
function audScore(a){return {authority:AUD_AUTH[a.authority]??null,interest:AUD_POSITION[a.position]??null}}
function audQuadrant(a){let s=audScore(a);if(s.authority===null||s.interest===null)return null;return `Q${s.authority>=7?(s.interest>=7?1:2):(s.interest>=7?4:3)}`}
function audSelect(field,values,value){return `<select name="${field}"><option value="">Sin clasificar</option>${Object.keys(values).map(k=>`<option ${value===k?'selected':''}>${safe(k)}</option>`).join('')}</select>`}
function audInput(label,field,value='',type='text'){return `<label>${label}<input type="${type}" name="${field}" value="${safe(value)}"></label>`}
function audienceManagementPage(x){let rows=x.audiences||[],counts={Q1:0,Q2:0,Q3:0,Q4:0};rows.forEach(a=>{let q=audQuadrant(a);if(q)counts[q]+=a.kind==='Grupo'?Number(a.population)||0:1});return `<section class="panel"><h2>Gestión estratégica de audiencias</h2><p class="muted">Registra personas o grupos, identifica su participación y explora estrategias. Las categorías son valoraciones de trabajo, no diagnósticos personales.</p><div class="flex"><button class="${audienceTab==='registro'?'primary':'secondary'}" onclick="audienceTab='registro';render()">Registro</button><button class="${audienceTab!=='registro'?'primary':'secondary'}" onclick="audienceTab='mapa';render()">Mapa y estrategias</button></div></section>${audienceTab==='registro'?audienceRegistration(x):audienceMap(x,counts)}`}
function audienceRegistration(x){let a=x.audiences.find(a=>a.id===audienceEditing)||{};return `<div class="grid"><section class="panel"><h2>${audienceEditing?'Editar':'Registrar'} audiencia</h2><form onsubmit="saveAudienceV22(event)"><div class="aud-v22-fields"><label>Tipo<select name="kind"><option ${a.kind!=='Grupo'?'selected':''}>Persona</option><option ${a.kind==='Grupo'?'selected':''}>Grupo</option></select></label>${audInput('Nombre / grupo *','name',a.name)}${audInput('Número de personas (grupos)','population',a.population||'','number')}${audInput('Cargo','job',a.job)}${audInput('Dirección','direction',a.direction)}${audInput('Equipo','team',a.team)}${audInput('Correo (opcional)','email',a.email,'email')}<label>Rol dentro del cambio<input name="changeRole" value="${safe(a.changeRole)}" placeholder="Ej. Líder, ejecutor, usuario"></label><label>Autoridad${audSelect('authority',AUD_AUTH,a.authority)}</label><label>Interés/influencia${audSelect('position',AUD_POSITION,a.position)}</label><label>Impacto<select name="impact"><option value="">Sin evaluar</option>${['Alto','Medio','Bajo'].map(v=>`<option ${a.impact===v?'selected':''}>${v}</option>`).join('')}</select></label>${audInput('Segmento','segment',a.segment)}</div><label>Impactos específicos<textarea name="specificImpact">${safe(a.specificImpact)}</textarea></label><label>Historial de cambio<textarea name="changeHistory">${safe(a.changeHistory)}</textarea></label><label>Evidencias de clasificación (opcional)<textarea name="classificationEvidence" placeholder="Hechos observados, fuente y fecha">${safe(a.classificationEvidence)}</textarea></label><button class="primary">${audienceEditing?'Guardar cambios':'Agregar audiencia'}</button> ${audienceEditing?'<button type="button" class="secondary" onclick="audienceEditing=null;render()">Cancelar</button>':''}</form></section><section class="panel"><h2>Carga masiva CSV</h2><p class="muted">Descarga una plantilla con categorías seleccionables y conserva la información existente. La importación admite columnas adicionales.</p><button class="secondary" onclick="downloadAudienceTemplateV22()">↓ Plantilla CSV</button><input type="file" accept=".csv,text/csv" onchange="previewAudienceCSVV22(this)"><div id="aud-v22-import"></div><h3>Audiencias (${x.audiences.length})</h3><div class="aud-v22-list">${x.audiences.map(a=>`<div class="aud-v22-row"><div><strong>${safe(a.name)}</strong><p class="muted">${safe(a.authority||'Sin autoridad')} · ${safe(a.position||'Sin posición')} · ${audQuadrant(a)||'Sin cuadrante'}</p></div><div class="flex"><button class="secondary" onclick="audienceEditing='${safe(a.id)}';render()">Editar</button><button class="secondary aud-danger" onclick="deleteAudienceV23('${safe(a.id)}')">Eliminar</button></div></div>`).join('')||'<div class="empty">No hay audiencias registradas.</div>'}</div></section></div>`}
function saveAudienceV22(e){e.preventDefault();let f=e.target,d=Object.fromEntries(new FormData(f));if(!d.name.trim())return alert('Indica un nombre');if(d.population&&(!Number.isInteger(Number(d.population))||Number(d.population)<0))return alert('La población debe ser un entero no negativo');let x=current(),a=x.audiences.find(a=>a.id===audienceEditing);if(!a){a={id:'aud-'+crypto.randomUUID()};x.audiences.push(a)}Object.assign(a,d,{name:d.name.trim()});audienceEditing=null;save();render()}
function deleteAudienceV23(id){
 const x=current(),a=x.audiences.find(a=>a.id===id);if(!a)return;
 const linked=(x.behaviors||[]).filter(b=>(b.audienceIds||[]).includes(id)).length;
 const warning=linked?`\nEstá vinculada a ${linked} comportamiento(s); se quitará esa asociación, pero se conservarán los comportamientos.`:'';
 if(!confirm(`¿Eliminar la audiencia «${a.name}»?${warning}\nEsta acción no se puede deshacer.`))return;
 x.audiences=x.audiences.filter(item=>item.id!==id);
 (x.behaviors||[]).forEach(b=>{if(Array.isArray(b.audienceIds))b.audienceIds=b.audienceIds.filter(aid=>aid!==id)});
 if(audienceEditing===id)audienceEditing=null;if(audienceSelected===id)audienceSelected=null;
 save();render();
}
function audPopulation(a){return a.kind==='Grupo'?Math.max(0,Number(a.population)||0):1}
function audPriority(a){return a.impact==='Alto'&&(a.position==='Probable Resistente'||a.position==='Saboteador Abierto'||a.position==='Saboteador Oculto')}
function audFocus(id){audienceSelected=id;render();document.getElementById('audience-detail-v23')?.scrollIntoView({block:'nearest',behavior:'smooth'})}
function audFilterQuadrant(q){audienceQuadrantFilter=audienceQuadrantFilter===q?'':q;audienceSelected=null;render()}
function audMapSearch(value){audienceFilter=value;const root=document.getElementById('aud-map-results');if(!root)return;root.querySelectorAll('[data-aud-search]').forEach(el=>{el.hidden=!el.dataset.audSearch.includes(value.toLocaleLowerCase('es'))});document.querySelectorAll('.aud-map-label').forEach(el=>{el.hidden=!!value&&!el.dataset.audSearch.includes(value.toLocaleLowerCase('es'))})}
function audSendStrategy(id,q,index){
 const x=current(),a=x.audiences.find(a=>a.id===id),strategy=AUD_STRATEGIES[q]?.[index];if(!a||!strategy)return;
 if(!confirm(`¿Crear una acción pendiente en Implementación para «${a.name}»?\n\n${strategy}`))return;
 x.actions=x.actions||[];
 x.actions.push({name:`${strategy} · ${a.name}`,title:`${strategy} · ${a.name}`,description:`Estrategia orientativa del mapa de audiencias (${q}). Validar pertinencia con evidencias.`,hypothesis:`Dado el posicionamiento registrado de ${a.name}, esperamos que ${strategy.toLocaleLowerCase('es')} favorezca su involucramiento. Hipótesis por validar.`,origin:'Diagnóstico',source:'Mapa de audiencias',audienceId:a.id,audienceName:a.name,quadrant:q,status:'Pendiente',createdAt:new Date().toISOString()});
 save();alert('Acción registrada como pendiente en Implementación. Revisa y completa sus datos allí.');
}
function audienceMap(x,counts){
 const all=x.audiences||[],positioned=all.filter(a=>audQuadrant(a)),unclassified=all.length-positioned.length;
 const filtered=positioned.filter(a=>!audienceQuadrantFilter||audQuadrant(a)===audienceQuadrantFilter);
 const total=all.reduce((n,a)=>n+audPopulation(a),0),priority=all.filter(audPriority).length;
 const overlaps={};
 const dots=filtered.map(a=>{
  const sc=audScore(a),key=sc.authority+'-'+sc.interest,idx=overlaps[key]||0;overlaps[key]=idx+1;
  const theta=idx*2.39996,r=idx?Math.min(30,9*Math.sqrt(idx)):0;
  const px=12+(sc.interest-4)/6*76,py=88-(sc.authority-5)/5*76;
  const color=a.position==='Promotor'?'#20c5aa':a.position==='Pasivo'?'#efb957':'#ed837f';
  const size=Math.min(30,13+Math.sqrt(audPopulation(a))*2);
  return `<button type="button" class="aud-map-label ${audienceSelected===a.id?'is-selected':''}" data-aud-search="${safe(a.name.toLocaleLowerCase('es'))}" style="left:clamp(5%,calc(${px}% + ${Math.cos(theta)*r}px),95%);top:clamp(6%,calc(${py}% + ${Math.sin(theta)*r}px),94%)" title="${safe(a.name)} · ${safe(a.authority)} · ${safe(a.position)}" onclick="audFocus('${safe(a.id)}')"><span class="aud-map-bubble" style="width:${size}px;height:${size}px;background:${color}"></span><span class="aud-map-name">${safe(a.name)}</span></button>`;
 }).join('');
 const selected=all.find(a=>a.id===audienceSelected);
 const detail=selected?`<section id="audience-detail-v23" class="panel aud-detail"><div class="flex" style="justify-content:space-between"><h3>${safe(selected.name)}</h3><button class="secondary" onclick="audienceSelected=null;render()">Cerrar ×</button></div><p class="muted">${safe(selected.kind||'Persona')} · ${audPopulation(selected)} persona(s) · ${safe(selected.team||selected.direction||'Sin equipo')}</p><p><b>Autoridad:</b> ${safe(selected.authority||'Sin clasificar')} (${audScore(selected).authority??'—'}) · <b>Posicionamiento:</b> ${safe(selected.position||'Sin clasificar')} (${audScore(selected).interest??'—'})</p><p><b>Impacto:</b> ${safe(selected.impact||'Sin evaluar')} · <b>Cuadrante:</b> ${audQuadrant(selected)||'Sin clasificar'}</p>${selected.classificationEvidence?`<p><b>Evidencias:</b> ${safe(selected.classificationEvidence)}</p>`:''}${audPriority(selected)?'<p class="notice">Revisión prioritaria sugerida: impacto alto y posible oposición. Contrasta la clasificación con evidencias.</p>':''}<h3>Estrategias orientativas</h3>${(AUD_STRATEGIES[audQuadrant(selected)]||[]).map((st,i)=>`<div class="aud-strategy-line"><span>${safe(st)}</span><button class="secondary" onclick="audSendStrategy('${safe(selected.id)}','${audQuadrant(selected)}',${i})">+ Llevar a Implementación</button></div>`).join('')||'<p class="muted">Clasifica la audiencia para visualizar estrategias.</p>'}</section>`:'';
 const quadrants=[['Q2','Consultar'],['Q1','Colaborar'],['Q3','Informar'],['Q4','Involucrar']];
 return `<section class="panel"><h2>Mapa y estrategias de audiencias</h2><p class="muted">Explora las audiencias y selecciona un punto para conocer sus características y acciones sugeridas. Puntuaciones según las categorías acordadas; corte alto: 7.</p><div class="aud-kpis"><div><b>${all.length}</b><small>Audiencias</small></div><div><b>${total}</b><small>Personas representadas</small></div><div><b>${priority}</b><small>Para revisión prioritaria</small></div><div><b>${unclassified}</b><small>Sin clasificar</small></div></div><div class="flex"><label class="aud-search">Buscar audiencia<input aria-label="Buscar audiencia" placeholder="Nombre de persona o grupo" value="${safe(audienceFilter)}" oninput="audMapSearch(this.value)"></label><button class="secondary" onclick="audienceQuadrantFilter='';audienceFilter='';render()">Limpiar filtros</button></div><div class="aud-map-v23"><div class="aud-map-quadrants">${quadrants.map(([q,label])=>`<button class="aud-quadrant ${audienceQuadrantFilter===q?'selected':''}" onclick="audFilterQuadrant('${q}')"><span>${q} · ${label}</span><strong>${counts[q]}</strong></button>`).join('')}</div>${dots||'<div class="aud-no-dots">No hay audiencias clasificadas en este filtro.</div>'}<div class="aud-axis-y">Autoridad ↑</div><div class="aud-axis-x">Interés / influencia →</div></div><div class="aud-legend"><span><i style="background:#20c5aa"></i> Promotor</span><span><i style="background:#efb957"></i> Pasivo</span><span><i style="background:#ed837f"></i> Posible oposición</span><span>El tamaño indica población</span></div>${detail}<h3>Audiencias en el mapa</h3><div id="aud-map-results" class="aud-results">${filtered.map(a=>`<button data-aud-search="${safe(a.name.toLocaleLowerCase('es'))}" class="aud-result" onclick="audFocus('${safe(a.id)}')"><b>${safe(a.name)}</b><small>${audQuadrant(a)} · ${safe(a.position)} · ${audPopulation(a)} persona(s)</small></button>`).join('')||'<p class="muted">No hay resultados.</p>'}</div><h3>Estrategias por cuadrante</h3><p class="muted">Selecciona un cuadrante para filtrar sus audiencias. Las estrategias son orientativas y deben contrastarse con evidencias.</p><div class="aud-strategies-grid">${quadrants.map(([q,label])=>`<section class="aud-strategy-card"><button class="aud-strategy-head" onclick="audFilterQuadrant('${q}')"><b>${q} · ${label}</b><span>${counts[q]} persona(s)</span></button>${AUD_STRATEGIES[q].map(s=>`<p>• ${safe(s)}</p>`).join('')}</section>`).join('')}</div></section>`;
}
function audienceStrategies(x,counts){return `<section class="panel"><h2>Estrategias por cuadrante</h2><p class="muted">Orientaciones iniciales: contrasta las acciones con el diagnóstico y la evidencia antes de aplicarlas.</p><div class="grid">${Object.entries(AUD_STRATEGIES).map(([q,items])=>`<section class="panel"><h3>${q} · ${{Q1:'Colaborar',Q2:'Consultar',Q3:'Informar',Q4:'Involucrar'}[q]} (${counts[q]})</h3>${items.map(t=>`<p>• ${safe(t)}</p>`).join('')}</section>`).join('')}</div><h3>Audiencias y recomendaciones</h3>${x.audiences.map(a=>{let q=audQuadrant(a);return `<div class="aud-v22-row"><div><strong>${safe(a.name)}</strong><p class="muted">${q||'Pendiente de clasificación'} · ${safe(a.position||'Sin posición')}</p></div><span>${q?AUD_STRATEGIES[q].map(safe).join(' · '):'Selecciona las categorías para obtener una orientación.'}</span></div>`}).join('')}</section>`}
const AUD_CSV_FIELDS=['nombre','tipo','poblacion','cargo','direccion','equipo','correo','rol_cambio','autoridad','interes_influencia','impacto','segmento','impactos_especificos','historial_cambio','evidencia'];
function downloadAudienceTemplateV22(){let header=AUD_CSV_FIELDS.join(','),example=['Líderes regionales','Grupo','12','Líder','Operaciones','Regional','','Patrocinador','Decisor','Promotor','Alto','','','',''].join(',');let b=new Blob(['\uFEFF'+header+'\r\n'+example],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='HACERLO_plantilla_audiencias_V22.csv';a.click();URL.revokeObjectURL(url)}
let audV22Rows=[];
async function previewAudienceCSVV22(input){let target=document.getElementById('aud-v22-import');audV22Rows=[];if(!input.files.length)return;try{let file=input.files[0];if(file.size>2e6)throw Error('Máximo 2 MB');let lines=parseAudienceCSV(await file.text());if(lines.length<2)throw Error('El archivo no tiene registros');let keys=lines.shift().map(v=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/[\s/]+/g,'_'));if(!keys.includes('nombre'))throw Error('Falta columna nombre');if(lines.length>2000)throw Error('Máximo 2000 registros');let seen=new Set();audV22Rows=lines.map((line,i)=>{let d=Object.fromEntries(keys.map((k,j)=>[k,(line[j]||'').trim()]));let errors=[];if(!d.nombre)errors.push('Nombre vacío');if(seen.has(d.nombre.toLowerCase()))errors.push('Nombre repetido');seen.add(d.nombre.toLowerCase());if(d.autoridad&&!Object.hasOwn(AUD_AUTH,d.autoridad))errors.push('Autoridad no reconocida');if(d.interes_influencia&&!Object.hasOwn(AUD_POSITION,d.interes_influencia))errors.push('Interés/influencia no reconocido');if(d.poblacion&&(!/^\d+$/.test(d.poblacion)))errors.push('Población inválida');return {d,errors,line:i+2}});let valid=audV22Rows.filter(r=>!r.errors.length);target.innerHTML=`<p>${valid.length} filas válidas · ${audV22Rows.length-valid.length} con errores</p>${audV22Rows.filter(r=>r.errors.length).slice(0,10).map(r=>`<p class="notice">Fila ${r.line}: ${safe(r.errors.join(', '))}</p>`).join('')}<label>Duplicados por nombre<select id="aud-v22-mode"><option value="skip">Omitir existentes</option><option value="update">Actualizar existentes</option></select></label><button class="primary" ${valid.length?'':'disabled'} onclick="commitAudienceCSVV22()">Importar ${valid.length}</button>`}catch(e){target.textContent='Error: '+e.message}}
function commitAudienceCSVV22(){let x=current(),mode=document.getElementById('aud-v22-mode').value,added=0,updated=0;let map={nombre:'name',tipo:'kind',poblacion:'population',cargo:'job',direccion:'direction',equipo:'team',correo:'email',rol_cambio:'changeRole',autoridad:'authority',interes_influencia:'position',impacto:'impact',segmento:'segment',impactos_especificos:'specificImpact',historial_cambio:'changeHistory',evidencia:'classificationEvidence'};for(let {d,errors} of audV22Rows){if(errors.length)continue;let a=x.audiences.find(a=>a.name.toLowerCase()===d.nombre.toLowerCase());if(a&&mode==='skip')continue;if(!a){a={id:'aud-'+crypto.randomUUID()};x.audiences.push(a);added++}else updated++;for(let [from,to] of Object.entries(map))if(d[from]!==undefined)a[to]=d[from]}audV22Rows=[];save();alert(`Importadas: ${added} nuevas, ${updated} actualizadas`);render()}
